{% set name = "diffpy.pdffit2" %}
{% set version = "1.4.4rc4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/diffpy_pdffit2/diffpy_pdffit2-{{ version }}.tar.gz
  sha256: d15fd7fbb4dec3a1dded67d289e179dedd68cae89865572651e734447e5be0f7

build:
  number: 0
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - gsl {{ gsl }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
    - setuptools-git-versioning >=2.0
    - gsl {{ gsl }}
  run:
    - python
    - setuptools
    - six
    - diffpy.structure
    - gsl {{ gsl }}

test: 
  requires:
    - pip
    - pytest
  source_files:
    - tests
  commands:
    - pip check
    - pip list
    - pytest

about:
  home: https://github.com/diffpy/diffpy.pdffit2
  summary: PDFfit2 - real space structure refinement program.
  description: |
    The diffpy.pdffit2 package provides functions for calculation and refinement of atomic pair distribution function 
    from crystal structure model. It is used as a computational engine by PDFgui, which provides a simple, fast, and 
    easy-to-use user interface for chemists, physicists, and materials scientists.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  doc_url: https://www.diffpy.org/doc/pdffit2
  dev_url: https://github.com/diffpy/diffpy.pdffit2

extra:
  recipe-maintainers:
    - bobleesj
    - dragonyanglong
    - sbillinge