{% set name = "diffpy.pdffit2" %}
{% set version = "1.4.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 45f053323bdc7f94d2e12766f8ee0b7d2d3db9efc100c104592cb2473c4577d2

build:
  number: 0
  skip: true  # [py<312]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - gsl {{ gsl }}
  host:
    - python
    - pip
    - setuptools
    - gsl {{ gsl }}
  run:
    - python
    - setuptools
    - six
    - diffpy.structure
    - gsl {{ gsl }}

test:
  imports:
    - diffpy
    - diffpy.pdffit2
    - diffpy.pdffit2.pdffit2
    - diffpy.pdffit2.ipy_ext
    - diffpy.pdffit2.tests
  requires:
    - pip
  commands:
    - pip check
    - python -c "import diffpy.pdffit2; print(diffpy.pdffit2.__version__)"

about:
  home: https://github.com/diffpy/diffpy.pdffit2
  summary: PDFfit2 - real space structure refinement program.
  description: |
    The diffpy.pdffit2 package provides functions for calculation and refinement of atomic pair distribution function 
    from crystal structure model. It is used as a computational engine by PDFgui, which provides a simple, fast, and 
    easy-to-use user interface for chemists, physicists, and materials scientists.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  doc_url: https://www.diffpy.org/doc/pdffit2
  dev_url: https://github.com/diffpy/diffpy.pdffit2

extra:
  recipe-maintainers:
    - bobleesj
    - dragonyanglong
    - sbillinge