{% set name = "diffpy.pdffit2" %}
{% set version = "1.5.0rc1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/d/diffpy_pdffit2/diffpy_pdffit2-{{ version }}.tar.gz
  sha256: 63807cc31232d256f35c404b4d127280adb5a10e98384111b896c69642c97e3e

build:
  number: 0
  skip: true # [py<311]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
    - setuptools-git-versioning >=2.0
  run:
    - python
    - setuptools
    - diffpy.structure

test: 
  requires:
    - pip
    - pytest
  source_files:
    - tests
  commands:
    - pip check
    - pip list
    - pytest

about:
  home: https://github.com/diffpy/diffpy.pdffit2
  summary: PDFfit2 - real space structure refinement to atomic pair distribution function.
  description: |
    The diffpy.pdffit2 package provides functions for calculation and refinement of atomic pair distribution function 
    from crystal structure model. It is used as a computational engine by PDFgui, which provides a simple, fast, and 
    easy-to-use user interface for chemists, physicists, and materials scientists.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  doc_url: https://www.diffpy.org/doc/pdffit2
  dev_url: https://github.com/diffpy/diffpy.pdffit2

extra:
  recipe-maintainers:
    - bobleesj
    - sbillinge
