{% set name = "diffpy.pdffit2" %}
{% set version = "1.6.0" %}
{% set python_min = "3.12" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/d/diffpy_pdffit2/diffpy_pdffit2-{{ version }}.tar.gz
  sha256: 11a65466f8790f5ac7ae45f2f3fc0d5d116d156d274bcfc079df653123d080e2

build:
  number: 1
  skip: true  # [py<312]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - gsl
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
    - setuptools-git-versioning >=2.0
    - gsl
  run:
    - python
    - setuptools
    - diffpy.structure
    - gsl

test:
  requires:
    - pip
    - pytest
  source_files:
    - tests
  commands:
    - pip check
    - pip list
    - pytest

about:
  home: https://github.com/diffpy/diffpy.pdffit2
  summary: PDFfit2 - real space structure refinement to atomic pair distribution function.
  description: |
    The diffpy.pdffit2 package provides functions for calculation and refinement of atomic pair distribution function 
    from crystal structure model. It is used as a computational engine by PDFgui, which provides a simple, fast, and 
    easy-to-use user interface for chemists, physicists, and materials scientists.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  doc_url: https://www.diffpy.org/doc/pdffit2
  dev_url: https://github.com/diffpy/diffpy.pdffit2

extra:
  recipe-maintainers:
    - Tieqiong
    - bobleesj
    - sbillinge
